# Generated by Django 5.2.7 on 2025-12-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mcq_answers',
            unique_together={('exam', 'student', 'question')},
        ),
    ]
