# Generated by Django 5.2.7 on 2025-10-31 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_formermember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth', models.URLField(blank=True, null=True)),
                ('twelth', models.URLField(blank=True, null=True)),
                ('degree', models.URLField(blank=True, null=True)),
                ('masters', models.URLField(blank=True, null=True)),
                ('marks_card', models.URLField(blank=True, null=True)),
                ('certificates', models.URLField(blank=True, null=True)),
                ('award', models.URLField(blank=True, null=True)),
                ('resume', models.URLField(blank=True, null=True)),
                ('id_proof', models.URLField(blank=True, null=True)),
                ('appointment_letter', models.URLField(blank=True, null=True)),
                ('offer_letter', models.URLField(blank=True, null=True)),
                ('releaving_letter', models.URLField(blank=True, null=True)),
                ('resignation_letter', models.URLField(blank=True, null=True)),
                ('achievement_crt', models.URLField(blank=True, null=True)),
                ('bonafide_crt', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('weekday', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_description', models.TextField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_closed_by', to=settings.AUTH_USER_MODEL)),
                ('closed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_closed_to', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('raised_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to=settings.AUTH_USER_MODEL)),
                ('notice_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_by', to=settings.AUTH_USER_MODEL)),
                ('notice_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
