# Generated by Django 5.2.7 on 2025-12-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_attendance_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user'], name='school_atte_user_id_f0a134_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='school_atte_date_1a45c0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['role'], name='school_atte_role_6dab83_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='school_atte_status_29a19d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'user'], name='school_atte_date_b7c197_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['role', 'date'], name='school_atte_role_5ea2aa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student'], name='school_stud_student_9444f4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['subject'], name='school_stud_subject_366113_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['teacher'], name='school_stud_teacher_20564e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['class_id'], name='school_stud_class_i_86f063_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date'], name='school_stud_date_646ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['status'], name='school_stud_status_3ecf89_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'student'], name='school_stud_date_b21875_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['class_id', 'date'], name='school_stud_class_i_babdfa_idx'),
        ),
    ]
