# Generated by Django 5.2.7 on 2025-12-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_mcq_answers_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]