# Generated by Django 5.2.7 on 2025-12-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_attendance_school_atte_user_id_f0a134_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
