# Generated by Django 5.2.7 on 2025-12-16 12:45

from django.db import migrations


def remove_duplicate_mcq_answers(apps, schema_editor):
    """
    Remove duplicate MCQ answers, keeping only the first record for each
    (exam_id, student_id) combination.
    """
    MCQ_Answers = apps.get_model('school', 'MCQ_Answers')
    
    # Find all duplicate combinations
    from django.db.models import Count
    duplicates = MCQ_Answers.objects.values('exam_id', 'student_id').annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    # For each duplicate combination, keep only the first record
    for dup in duplicates:
        if dup['student_id'] is None:
            # Skip template records (where student_id is None)
            continue
            
        # Get all records for this combination
        records = MCQ_Answers.objects.filter(
            exam_id=dup['exam_id'],
            student_id=dup['student_id']
        ).order_by('id')
        
        # Keep the first record and delete the rest
        records_to_delete = records[1:]
        for record in records_to_delete:
            record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_program_coordinator_name'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_mcq_answers, reverse_code=migrations.RunPython.noop),
    ]