# Generated by Django 5.2.7 on 2025-12-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_duplicate_mcq_answers'),
    ]
    operations = [
        migrations.AlterUniqueTogether(
            name='mcq_answers',
            unique_together={('exam', 'student')},
        ),
    ]