# Generated by Django 5.2.7 on 2025-10-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by_role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('Principal', 'Principal'), ('Management', 'Management'), ('Admin', 'Admin')], default='Admin', max_length=20),
        ),
    ]
