# Generated by Django 5.2.7 on 2025-12-06 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_studentattendance_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.class')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.subject')),
                ('sub_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ_Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_1', models.TextField()),
                ('option_2', models.TextField()),
                ('option_3', models.TextField()),
                ('option_4', models.TextField()),
                ('correct_option', models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')])),
                ('result', models.BooleanField(default=False)),
                ('student_answer', models.IntegerField(blank=True, choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_answers', to='school.exam')),
            ],
        ),
    ]