# Generated by Django 5.2.7 on 2025-10-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_attendance_marked_by_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='class_enrolled',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_enrolled',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_enrolled',
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_name',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
