# Generated by Django 5.2.7 on 2025-10-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_timetable_class_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='issue',
            table='school_issues',
        ),
    ]
