# Generated by Django 5.2.7 on 2025-12-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_add_student_answer_and_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.IntegerField(unique=True),
        ),
    ]
