# Generated by Django 5.2.7 on 2025-12-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_add_id_field_to_exam'),
    ]

    operations = [
        # Drop the foreign key constraint from MCQ_Answers first
        migrations.RunSQL(
            "ALTER TABLE school_mcq_answers DROP CONSTRAINT IF EXISTS school_mcq_answers_exam_id_3807debb_fk_school_exam_exam_id;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Drop the current primary key constraint
        migrations.RunSQL(
            "ALTER TABLE school_exam DROP CONSTRAINT IF EXISTS school_exam_pkey;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Make id the new primary key
        migrations.RunSQL(
            "ALTER TABLE school_exam ADD CONSTRAINT school_exam_pkey PRIMARY KEY (id);",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Copy data from exam_id to id where id is NULL
        migrations.RunSQL(
            "UPDATE school_exam SET id = exam_id WHERE id IS NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Make id non-nullable
        migrations.RunSQL(
            "ALTER TABLE school_exam ALTER COLUMN id SET NOT NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Create sequence for id field auto-increment
        migrations.RunSQL(
            "CREATE SEQUENCE IF NOT EXISTS school_exam_id_seq;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Set the sequence as default for id field
        migrations.RunSQL(
            "ALTER TABLE school_exam ALTER COLUMN id SET DEFAULT nextval('school_exam_id_seq');",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Set the sequence to be owned by the id column
        migrations.RunSQL(
            "ALTER SEQUENCE school_exam_id_seq OWNED BY school_exam.id;",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Set the sequence value to max(id) + 1
        migrations.RunSQL(
            "SELECT setval('school_exam_id_seq', COALESCE((SELECT MAX(id) FROM school_exam), 1), true);",
            reverse_sql=migrations.RunSQL.noop
        ),
        
        # Add new foreign key constraint pointing to the id column
        migrations.RunSQL(
            "ALTER TABLE school_mcq_answers ADD CONSTRAINT school_mcq_answers_exam_id_fk FOREIGN KEY (exam_id) REFERENCES school_exam(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]