# Generated by Django 5.2.7 on 2025-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_rename_appointment_letter_document_admit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+')], max_length=3, null=True),
        ),
    ]
