# Generated by Django 5.2.7 on 2025-12-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_switch_exam_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_id',
        ),
    ]
