# Generated by Django 5.2.7 on 2025-12-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_exam_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, default='Untitled Exam'),
        ),
    ]