# Generated by Django 5.2.7 on 2025-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_teacher_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Graded', 'Graded'), ('Late', 'Late')], default='Assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='timetable',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
