# Generated by Django 5.2.7 on 2025-11-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_assignment_section_assignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
