# Generated by Django 5.2.7 on 2025-11-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_activity_financetransaction_program_project_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
