# Generated by Django 5.2.7 on 2025-11-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_feepayment_remaining_amount_feepayment_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
