# Generated by Django 5.2.7 on 2025-11-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_add_marked_by_role_to_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sec',
            field=models.CharField(default='NA', max_length=15),
        ),
    ]