# Generated by Django 5.2.7 on 2025-11-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_add_sec_field_to_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sec',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
