# Generated by Django 5.2.7 on 2025-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_attendance_sec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sec',
            field=models.CharField(default='NA', max_length=15),
        ),
    ]
