# Generated by Django 5.2.7 on 2025-11-07 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_attendance_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportdetails',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
