# Generated by Django 5.2.7 on 2025-11-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_remove_transportdetails_student_attendance_remarks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransportDetails',
        ),
    ]
