# Generated by Django 5.2.7 on 2025-11-07 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_delete_transportdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_point', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_point', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
