# Generated by Django 5.2.7 on 2025-11-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_transportdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Absent', editable=False, max_length=20),
        ),
    ]
