# Generated by Django 5.2.7 on 2025-11-10 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='section',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='section',
        ),
        migrations.AddField(
            model_name='activity',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='school.class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='school.class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='school.class'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.class'),
        ),
        migrations.AddField(
            model_name='project',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='school.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='school.class'),
        ),
    ]
