# Generated by Django 5.2.6 on 2025-11-10 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_remove_activity_class_name_remove_activity_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='school.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_classteacher',
            field=models.BooleanField(default=False),
        ),
    ]
