# Generated by Django 5.2.6 on 2025-11-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_teacher_class_id_teacher_is_classteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
