# Generated by Django 5.2.7 on 2025-11-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_teacher_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_name',
        ),
    ]
