# Generated by Django 5.2.6 on 2025-11-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_remove_teacher_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sec',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
