# Generated by Django 5.2.6 on 2025-11-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_teacher_sec'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE school_student RENAME COLUMN class_id TO class_id_id",
            reverse_sql="ALTER TABLE school_student RENAME COLUMN class_id_id TO class_id"
        ),
        migrations.RunSQL(
            "ALTER TABLE school_teacher RENAME COLUMN class_id TO class_id_id",
            reverse_sql="ALTER TABLE school_teacher RENAME COLUMN class_id_id TO class_id"
        ),
        migrations.RunSQL(
            "ALTER TABLE school_feestructure RENAME COLUMN class_id TO class_id_id",
            reverse_sql="ALTER TABLE school_feestructure RENAME COLUMN class_id_id TO class_id"
        ),
        migrations.RunSQL(
            "ALTER TABLE school_assignment RENAME COLUMN class_id TO class_id_id",
            reverse_sql="ALTER TABLE school_assignment RENAME COLUMN class_id_id TO class_id"
        ),
        migrations.RunSQL(
            "ALTER TABLE school_timetable RENAME COLUMN class_id TO class_id_id",
            reverse_sql="ALTER TABLE school_timetable RENAME COLUMN class_id_id TO class_id"
        ),
        migrations.RunSQL(
            "ALTER TABLE school_attendance RENAME COLUMN class_id TO class_id_id",
            reverse_sql="ALTER TABLE school_attendance RENAME COLUMN class_id_id TO class_id"
        ),
        migrations.RunSQL(
            "ALTER TABLE school_project RENAME COLUMN class_id TO class_id_id",
            reverse_sql="ALTER TABLE school_project RENAME COLUMN class_id_id TO class_id"
        ),
        migrations.RunSQL(
            "ALTER TABLE school_activity RENAME COLUMN class_id TO class_id_id",
            reverse_sql="ALTER TABLE school_activity RENAME COLUMN class_id_id TO class_id"
        ),
    ]
