# Generated by Django 5.2.6 on 2025-11-11 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_attendance_data(apps, schema_editor):
    # Migrate existing student attendance data to user-based attendance
    Attendance = apps.get_model('school', 'Attendance')
    User = apps.get_model('school', 'User')
    Student = apps.get_model('school', 'Student')
    
    # For each attendance record, link it to the user
    for attendance in Attendance.objects.all():
        try:
            # Get the student and then the user
            student = Student.objects.get(email=attendance.student_id)
            attendance.user = student.email
            attendance.save()
        except (Student.DoesNotExist, AttributeError):
            # If we can't find the student, delete the attendance record
            attendance.delete()


def reverse_migrate_attendance_data(apps, schema_editor):
    # This is a one-way migration, reverse operation would be complex
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_fix_class_id_column_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_attendance_data, reverse_migrate_attendance_data),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'date')},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_by_role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Principal', 'Principal'), ('Management', 'Management'), ('Admin', 'Admin')], default='Admin', max_length=20),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sec',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
