# Generated by Django 5.2.6 on 2025-11-11 11:15

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def ensure_user_field_populated(apps, schema_editor):
    # Ensure all attendance records have a user
    Attendance = apps.get_model('school', 'Attendance')
    
    # Delete any attendance records that don't have a user (shouldn't be any after previous migration)
    Attendance.objects.filter(user__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_modify_attendance_for_generic_users'),
    ]

    operations = [
        migrations.RunPython(ensure_user_field_populated),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
    ]