# Generated by Django 5.2.6 on 2025-11-11 12:00

from django.db import migrations


def enforce_staff_only_face_attendance(apps, schema_editor):
    # This migration ensures that the application logic properly excludes students
    # from face recognition attendance. The actual enforcement is in the view code,
    # so this migration is just for documentation purposes.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_make_attendance_user_non_nullable'),
    ]

    operations = [
        migrations.RunPython(enforce_staff_only_face_attendance),
    ]