# Generated by Django 5.2.6 on 2025-11-11 12:30

from django.db import migrations


def fix_teacher_is_classteacher_field(apps, schema_editor):
    # Fix any existing teacher records that might have null values for is_classteacher
    Teacher = apps.get_model('school', 'Teacher')
    
    # Update all teachers with null is_classteacher to False
    Teacher.objects.filter(is_classteacher__isnull=True).update(is_classteacher=False)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_enforce_staff_only_face_attendance'),
    ]

    operations = [
        migrations.RunPython(fix_teacher_is_classteacher_field),
    ]