# Generated by Django 5.2.6 on 2025-11-11 13:00

from django.db import migrations


def ensure_teacher_is_classteacher_default(apps, schema_editor):
    # Ensure all teachers have is_classteacher properly set
    Teacher = apps.get_model('school', 'Teacher')
    
    # Update all teachers with null is_classteacher to False
    Teacher.objects.filter(is_classteacher__isnull=True).update(is_classteacher=False)


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_fix_teacher_is_classteacher_field'),
    ]

    operations = [
        migrations.RunPython(ensure_teacher_is_classteacher_default),
    ]