# Generated by Django 5.2.6 on 2025-11-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_ensure_teacher_is_classteacher_default'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE school_teacher ALTER COLUMN is_classteacher SET DEFAULT false;",
            reverse_sql="ALTER TABLE school_teacher ALTER COLUMN is_classteacher DROP DEFAULT;"
        ),
    ]