# Generated by Django 5.2 on 2025-11-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_fix_teacher_is_classteacher_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='role',
            field=models.CharField(editable=False, max_length=20, default=''),
        ),
        migrations.RunSQL(
            "UPDATE school_attendance sa SET role = su.role FROM school_user su WHERE sa.user_id = su.email;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_by_role',
        ),
    ]