# Generated by Django 5.2.7 on 2025-11-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_update_attendance_role_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='role',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
