# Generated by Django 5.2.6 on 2025-11-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_alter_attendance_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='student_submission',
            field=models.URLField(blank=True, null=True),
        ),
    ]
