# Generated by Django 5.2.7 on 2025-11-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_create_submitted_assignment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to='school.student', to_field='email'),
        ),
    ]
