# Generated by Django 5.2.6 on 2025-11-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='barcode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='barcode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='barcode_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='barcode_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
