# Generated by Django 5.2.6 on 2025-11-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_move_barcode_url_to_role_models'),
    ]

    operations = [
    ]
